// Code generated by mockery v2.10.4. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/rudiarta/boilerplate-go/internal/pkg/model"
	mock "github.com/stretchr/testify/mock"
)

// AccountRepository is an autogenerated mock type for the AccountRepository type
type AccountRepository struct {
	mock.Mock
}

// Insert provides a mock function with given fields: ctx, account
func (_m *AccountRepository) Insert(ctx context.Context, account model.Account) error {
	ret := _m.Called(ctx, account)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, model.Account) error); ok {
		r0 = rf(ctx, account)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
